// <auto-generated />
namespace WebStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddContent1FieldOnSlide : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddContent1FieldOnSlide));
        
        string IMigrationMetadata.Id
        {
            get { return "201707080035527_AddContent1FieldOnSlide"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
